In [1]:
import time
import pandas as pd
import numpy as np
import matplotlib.pyplot as plt
import matplotlib.patheffects as PathEffects
import seaborn as sns
from src.data.DataLoader import get_dataset

# zuerst files die ich brauche temporär downloaden oder direkt laden mittels library, dann hat man es lokal
#      und von dort aus richtigen Pfad nehmen
# get out_dir (ist in den runs in out_dir eingespeichert)
# dann files öffnen
# in pd dataframes laden: pd.read_csv(out_dir + "/file")
# dann mit plot aus tutorial anzeigen lassenfrom

sns.set_style('darkgrid')
sns.set_palette('muted')
sns.set_context("notebook", font_scale=1.5,
                rc={"lines.linewidth": 2.5})
#data_handler, d_args = get_handler_and_args("CIFAR10")
# S: Das sind die Roh-Daten, die (bzw. X_tr) müssen mit PCA oder Tsne transformiert werden.
# Dann werden diese Daten im zweidimensionalen Raum geplottet
X_tr, Y_tr, X_te, Y_te = get_dataset("CIFAR10")
rng = np.random.RandomState(0)
colors = rng.rand(10)
colors
len(Y_tr)

Files already downloaded and verified
Files already downloaded and verified


50000

In [2]:
Y_tr

tensor([6, 9, 9,  ..., 9, 1, 1])

In [21]:
path = 'bp_prop_clustersize/fcb53f24c6674a61bc6f21b1f5ced903'
# S: das sind die die selektiert wurden, die müssen gehighlighted werden
sampled_data = pd.read_csv("/Users/ilijanaspasojevic/PycharmProjects/dmbal/src/remote_files/" +  path + "/2_statistics.csv")
sampled_data
budget_data = pd.read_csv("/Users/ilijanaspasojevic/PycharmProjects/dmbal/src/remote_files/" + path + "/2_budget.csv")
budget_data

Unnamed: 0    idx  centroid
0              0  17211         8
1              1     95         2
2              2   7426         8
3              3  38450         1
4              4  44266         8
...          ...    ...       ...
9995        9995  47440         8
9996        9996    478         8
9997        9997  30516         3
9998        9998  20009         8
9999        9999    643         4

[10000 rows x 3 columns]

In [22]:
def label_scatter(data_points, sampled, labels):
    # choose a color palette with seaborn.
    num_classes = len(np.unique(labels))
    print(num_classes)
    palette = np.array(sns.color_palette("hls", num_classes))
    print(palette)

    # create a scatter plot.
    f = plt.figure(figsize=(8, 8))
    ax = plt.subplot(aspect='equal')
    #c=palette[labels.astype(np.int)
    weights_datapoints = np.arange(1, 11)
    weights_sampled = np.arange(1, len(sampled)+1)
    #c=label, cmap=matplotlib.colors.ListedColormap(colors)
    sc_data_points = ax.scatter(data_points[:,0], data_points[:,1], lw=0, s=40, c=labels, cmap='Greys')
    sc_sampled = ax.scatter(sampled[:,0], sampled[:,1], lw=0, s=40, c='red')
    plt.xlim(-25, 25)
    plt.ylim(-25, 25)
    ax.axis('off')
    ax.axis('tight')

    # add the labels for each digit corresponding to the label
    txts = []

#    for i in range(num_classes):

        # Position of each label at median of data points.

#        xtext, ytext = np.median(x[labels == i, :], axis=0)
#        txt = ax.text(xtext, ytext, str(i), fontsize=24)
#        txt.set_path_effects([
#            PathEffects.Stroke(linewidth=5, foreground="w"),
#            PathEffects.Normal()])
#        txts.append(txt)

    #return f, ax, sc_data_points, sc_sampled, txts


In [23]:
#from sklearn.decomposition import PCA
from sklearn.manifold import TSNE

time_start = time.time()

#pca = PCA()
# S: hier vermutlich:
budget_tr = X_tr[budget_data['idx']]
x = budget_tr.reshape(budget_tr.shape[0], -1)
print(x)

[[101 109 131 ... 150 140 138]
 [246 254 119 ... 243 231 150]
 [134 138 121 ...  98 122 106]
 ...
 [ 94 101 114 ... 115 113 118]
 [198 194 189 ...  26  26  26]
 [255 252 255 ... 145 137 148]]


In [24]:
X_tr[sampled_data['img_id']]

array([[[[180, 169, 135],
         [185, 174, 142],
         [193, 183, 155],
         ...,
         [200, 192, 164],
         [199, 191, 164],
         [199, 191, 166]],

        [[199, 198, 164],
         [210, 208, 176],
         [209, 206, 175],
         ...,
         [214, 210, 176],
         [214, 210, 178],
         [218, 213, 183]],

        [[194, 195, 164],
         [195, 195, 164],
         [202, 199, 168],
         ...,
         [208, 206, 174],
         [213, 211, 180],
         [219, 217, 188]],

        ...,

        [[213, 198, 169],
         [211, 198, 168],
         [206, 194, 164],
         ...,
         [173, 176, 149],
         [178, 182, 155],
         [169, 175, 147]],

        [[178, 163, 138],
         [182, 168, 143],
         [192, 180, 154],
         ...,
         [199, 193, 165],
         [205, 200, 172],
         [198, 194, 166]],

        [[207, 194, 173],
         [213, 201, 180],
         [199, 190, 168],
         ...,
         [222, 210, 188],
        

In [25]:
print(len(x))

10000


In [26]:
#sampled_data['img_id']
Sampled = X_tr[sampled_data['img_id']]
sampled = Sampled.reshape(Sampled.shape[0], -1)

In [27]:
#pca_result_data_points = pca.fit_transform(x)
#pca_result_sampled = pca.fit_transform(sampled_data)
tsne_budget = TSNE(random_state=10).fit_transform(x)
print(tsne_budget)

[[-24.711706   -8.04276  ]
 [ 10.538679    7.8123116]
 [  2.266598    7.9441586]
 ...
 [-31.95651    -2.5964983]
 [-33.759457  -25.535217 ]
 [ 45.977375   -0.936213 ]]


In [ ]:
#pca_result_sampled = pca.fit_transform(sampled)
tsne_sampled = TSNE(random_state=10).fit_transform(sampled)

In [ ]:
budget_data['centroid']

In [ ]:
label_scatter(top_two_comp.values, top_two_comp_sampled.values, budget_data['centroid'])