In [7]:
import time
import pandas as pd
import numpy as np
import matplotlib.pyplot as plt
import matplotlib.patheffects as PathEffects
import seaborn as sns
from src.data.DataLoader import get_dataset

# zuerst files die ich brauche temporär downloaden oder direkt laden mittels library, dann hat man es lokal
#      und von dort aus richtigen Pfad nehmen
# get out_dir (ist in den runs in out_dir eingespeichert)
# dann files öffnen
# in pd dataframes laden: pd.read_csv(out_dir + "/file")
# dann mit plot aus tutorial anzeigen lassenfrom 

sns.set_style('darkgrid')
sns.set_palette('muted')
sns.set_context("notebook", font_scale=1.5,
                rc={"lines.linewidth": 2.5})
#data_handler, d_args = get_handler_and_args("CIFAR10")
# S: Das sind die Roh-Daten, die (bzw. X_tr) müssen mit PCA oder Tsne transformiert werden. 
# Dann werden diese Daten im zweidimensionalen Raum geplottet 
X_tr, Y_tr, X_te, Y_te = get_dataset("CIFAR10")
rng = np.random.RandomState(0)
colors = rng.rand(10)
colors
len(Y_tr)

Files already downloaded and verified
Files already downloaded and verified


50000

In [8]:
Y_tr

tensor([6, 9, 9,  ..., 9, 1, 1])

In [9]:
path1 = 'bp_lmo/52cb83fe7df64b5baf369ee172b4194b'
path2 = 'bp_lmo/cf55da05f9014799a7ea6c4c6f189e8b'
path3 = 'bp_smo/9ab696d7bdad462e9fc2434c7c34eac6'
# S: das sind die die selektiert wurden, die müssen gehighlighted werden
sampled_data = pd.read_csv("/Users/ilijanaspasojevic/PycharmProjects/dmbal/src/remote_files/" + path3 + "/0_statistics.csv")
sampled_data

Unnamed: 0  img_id
0             0   48099
1             1   23599
2             2   13399
3             3   39885
4             4    7780
..          ...     ...
995         995   43358
996         996   32881
997         997   44565
998         998   39923
999         999   19093

[1000 rows x 2 columns]

In [10]:
def label_scatter(data_points, sampled, labels):
    # choose a color palette with seaborn.
    num_classes = len(np.unique(labels))
    print(num_classes)
    palette = np.array(sns.color_palette("hls", num_classes))
    print(palette)

    # create a scatter plot.
    f = plt.figure(figsize=(8, 8))
    ax = plt.subplot(aspect='equal')
    #c=palette[labels.astype(np.int)
    weights_datapoints = np.arange(1, 11)
    weights_sampled = np.arange(1, len(sampled)+1)
    #c=label, cmap=matplotlib.colors.ListedColormap(colors)
    sc_data_points = ax.scatter(data_points[:,0], data_points[:,1], lw=0, s=40, c=labels, cmap='Greys')
    sc_sampled = ax.scatter(sampled[:,0], sampled[:,1], lw=0, s=40, c='red')
    plt.xlim(-25, 25)
    plt.ylim(-25, 25)
    ax.axis('off')
    ax.axis('tight')
    txts = []


In [19]:
#from sklearn.decomposition import PCA
from sklearn.manifold import TSNE

time_start = time.time()

# S: hier vermutlich:
x = X_tr.reshape(X_tr.shape[0], -1)
print(x)

[[ 59  62  63 ... 123  92  72]
 [154 177 187 ... 143 133 144]
 [255 255 255 ...  80  86  84]
 ...
 [ 35 178 235 ...  12  31  50]
 [189 211 240 ... 195 190 171]
 [229 229 239 ... 163 163 161]]


In [20]:
print(len(x))

50000


In [21]:
#sampled_data['img_id']
Sampled = X_tr[sampled_data['img_id']]
sampled = Sampled.reshape(Sampled.shape[0], -1)
sampled

array([[101, 160, 211, ...,  22,  20,  22],
       [252, 253, 255, ..., 155, 158, 110],
       [ 95, 126, 175, ..., 118, 112,  87],
       ...,
       [168, 131,  97, ..., 157, 123,  75],
       [155, 176, 120, ...,  79, 120,  59],
       [209, 208, 191, ..., 145, 141,  99]], dtype=uint8)

In [ ]:
#pca_result_data_points = pca.fit_transform(x) 
tsne_X_tr = TSNE(random_state=10).fit_transform(x)
print(tsne_X_tr)

In [18]:
#pca_result_sampled = pca.fit_transform(sampled)
tsne_sampled = TSNE(random_state=10).fit_transform(sampled)
tsne_sampled

array([[ 15.969514  ,   6.43574   ],
       [ -1.2665759 ,   0.8130914 ],
       [ -3.3558435 ,   6.6427326 ],
       ...,
       [  0.11111231,  -6.673801  ],
       [-19.599854  ,  -1.3017479 ],
       [ -5.9116535 , -11.870515  ]], dtype=float32)

In [ ]:
#pca_df = pd.DataFrame(columns = ['pca1','pca2','pca3','pca4'])

#pca_df['pca1'] = pca_result_data_points[:,0]
#pca_df['pca2'] = pca_result_data_points[:,1]
#top_two_comp = pca_df[['pca1','pca2']]
#print(top_two_comp)

In [ ]:
#pca_df_sampled = pd.DataFrame(columns = ['pca1','pca2','pca3','pca4'])

#pca_df_sampled['pca1'] = pca_result_sampled[:,0]
#pca_df_sampled['pca2'] = pca_result_sampled[:,1]
#top_two_comp_sampled = pca_df_sampled[['pca1','pca2']]
#print(top_two_comp_sampled)

In [ ]:
label_scatter(tsne_X_tr, tsne_sampled, Y_tr)